export const SELECT_PIZZA_TYPE = 'SELECT_PIZZA_TYPE';
export const SELECT_PIZZA_COMBO = 'SELECT_PIZZA_SIZE';
export const SELECT_DRINK = 'SELECT_DRINK';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
